version: '3'
services:
  wrattler_client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    # stdin_open: true
    # tty: true
    depends_on:
    - wrattler_python_service
    - wrattler_data_store
    networks:
    - wrattler_nw
    volumes:
      - ./client:/app
    entrypoint: /bin/bash
    command: "./entrypoint.sh"

  wrattler_python_service:
    build:
      context: server/python
      dockerfile: Dockerfile
    ports:
    - "7101:7101"
    environment:
     - FLASK_CONFIGURATION=default
     - DATASTORE_URI=http://wrattler_wrattler_data_store_1:7102
    networks:
    - wrattler_nw

  wrattler_data_store:
    build:
      context: server/data-store
      dockerfile: Dockerfile
    ports:
    - "7102:7102"
    networks:
    - wrattler_nw

networks:
  wrattler_nw:
    driver: bridge
