title: Wrattler
baseurl: /wrattler
url: "https://tbd"

# Build settings
markdown: kramdown
highlighter: rouge

theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - .git/

# Serve settings
port: 8081
host: localhost
